### PR TITLE
Handle text overflow

### LINKED ISSUE #2: Handle text overflow
Handle text overflow outside of layouts through culling and clipping.

Culling:
- We could cull on the CPU, e.g. if all or any glyph's vertex is outside the layout then we could skip it
  - We could also clip on the CPU at this point if we want, see note below

Clipping:
- When one layout is used per `render`, clipping with scissor could be handled outside of glyphon or by glyphon setting the scissor
- When multiple layouts are used, we'd probably need to handle clipping through shader discard or clip on the CPU (e.g. clip the vertices and sample the glyph from the remaining area)

### PR DESCRIPTION
**Pull request by grovesNL**
Cull glyphs fully outside the bounds, and clip glyphs intersecting the bounds. This is all done on the CPU for now.

Fixes #2

We'll wait on a new version of fontdue to be published before merging.

### CODE REVIEW

**Comment by genusistimelord** [comment]
Would like to note that this is a nice feature to reduce Buffer sizes being sent to the GPU. you should also include Region Scissor Clipping. Example Of it below with Queued Rendering in the current wgpu_glyph library hector made.
https://github.com/genusistimelord/wgpu_glyph/blob/query/src/pipeline.rs#L380
 I would recommend Supporting this as this will allow Text to be Clipped to a Region preventing it from bleeding over into Other Areas it should not.

**Comment by grovesNL** [comment]
I may be misunderstanding, but scissor shouldn't be necessary for now. The approach in this PR already clips any glyphs that intersect the bounds of its `layout`, or culled if the glyph is fully outside the `layout`.

**Comment by genusistimelord** [comment]
I think it has more to do with Looks, for example it can still do what hide does But the last glyph instead of removing you let it stay and scissor it instead. this would show a partial Text rendering in lets say a single line Textbox.  it could expand the Enum to add it with a Region for it.

**Comment by grovesNL** [comment]
With this PR the hello-world example looks like this:

image
The glyphs in the top line of the "abc..." line (in the bottom square) are clipped instead of culled, so the scissor shouldn't be necessary here if I'm understanding correctly

**Comment by genusistimelord** [comment]
Oh I see sorry, had to look at the code closer, I thought it was just culling anything that would reach the border. But yeah you are instead Setting the x,y, width and height to clip the Glyph within the Atlas itself.

**Comment by grovesNL** [comment]
We'll just merge this for now instead of waiting for fontdue to release. We can still backport any changes into a release branch if we need to make a release in the meantime.

**Pull request merged**
