### PR TITLE
add render_range method

### PR DESCRIPTION
**Pull request by BillyDM**
I need the ability to only render a certain range of text areas instead of rendering all of them at once, so this PR adds a method to do that.

### CODE REVIEW

**Comment by grovesNL** [comment]
Hi! 👋 Thanks for the PR. Could you explain more about the context and why it could be useful to render a range vs. filtering to the ranges you want during `prepare`?

**Comment by BillyDM** [comment]
I'm creating a middleware vector graphics/texture graphics library for my GUI library. I want to batch all rendering primitives with the same z index and the same clipping rectangle together to minimize the amount of draw calls, and also to cache those rendering primitives for reuse.

I can't render all the text primitives at once because other primitives with a higher z index could be drawn on top of them, and then more text could be drawn on top of that (i.e. like in a node editor).

I also can't call `prepare` and `render` multiple times for each batch because `prepare` requires borrowing the `TextRenderer` as mutable, meaning I would have to separate each batch into a separate render pass (not ideal for performance).

**Comment by BillyDM** [comment]
When I think about it, it would be nice to also be able to cache sections of the vertex/index buffers directly for text areas that haven't changed instead of recalculating the vertex/index for every glyph every frame.

That might be outside the scope of `glyphon` though. If you think that functionality could fit with the vision of glyphon I could add it, or if not I might be better off implementing glyph rendering directly into my library.

**Comment by grovesNL** [comment]
That makes sense. There are a couple different ways to handle this right now so I'd be interested if they might already work for that use case:

- You can use a separate text renderer for each z-index layer/however you'd like to group them (e.g. if it's likely some groups at the same z-index are static while others are dynamic).
- You can pass the depth/z-index as metadata and let hardware depth testing automatically handle this without needing to batch separate text layers. glyphon can still clip the text areas in this case, but you'd still have to scissor the non-text parts.

**Comment by BillyDM** [comment]
Ah, I haven't thought about using hardware depth testing. I'm not sure exactly how it works though. Does depth testing still work across multiple batches with different scissoring rectangles?

**Comment by BillyDM** [comment]
Do you think using a depth buffer is overkill for a 2D graphics library?

**Comment by BillyDM** [comment]
Using a separate text renderer for each layer could work, although I still think it makes more sense to have just a single wgpu buffer and render a slice of that buffer for each layer.

**Comment by grovesNL** [comment]
> Do you think using a depth buffer is overkill for a 2D graphics library? Or is it a legitimate recommended way to go?

Not overkill at all! I think it's a great way to do it. I'm doing something similar for a 2D application and it's a pretty common technique for 2D games. Sometimes this allows the CPU implementation to be simplified, so it can improve performance overall.

> Using a separate text renderer for each layer could work, although I still think it makes more sense to have just a single wgpu buffer and render a slice of that buffer for each layer.

We could possibly look at sharing a buffer between renderers, but you run into problems sometimes when you need to display some extra characters at some point partway into the buffer. So there's a trade-off between sharing vs. having to possibly re-record a lot of static text areas just because something earlier in the buffer grew a bit.

**Comment by BillyDM** [comment]
Oh but wait, the depth buffer technique doesn't really work if you have semi-transparent objects or text (not uncommon in a complex GUI).

**Comment by BillyDM** [comment]
So my idea is that we can just cache the vertex buffer part for text areas that haven't changed. Then when rendering, if the renderer detects that the text area hasn't changed (and that the text atlas hasn't been trimmed), then instead of repopulating that part of the vertex buffer one glyph at a time, we just push the cached slice into the vertex buffer. Then populating the index buffer should be really cheap since it's just a repeating sequence with an offset.

**Comment by BillyDM** [comment]
I found a way to make it work by having a separate text renderer for each layer. So I think I'll close this PR.

**Pull request closed without merging**
